packages:
  - '.'
  - web
minimumReleaseAgeExclude:
  - mastra
  - "@mastra/*"
allowBuilds:
  '@livekit/local-inference': true
  agent-browser: true
  bufferutil: true
  edgedriver: false
  esbuild: true
  geckodriver: false
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  unrs-resolver: false
  utf-8-validate: true
